### ISSUE TITLE
Hello ! No issue , just a question, to check if it's possible

### ISSUE THREAD

**Issue by Maureks** [jaylac2000/qb-communityservice#1]
hey! 

the script is wonderfull , I was just wandering if theres a way , to give the permissions of /comserv to staff members too , instead of only the policejob .

thanks for the attention , thanks for the script !

EDIT : 

No such export fetchSync in resource oxmysql

it's giving this error 

EDIT : Error of fetchSync fixed

**Comment by jaylac2000** [comment]
yup added and fix sql errors. redownload

**Comment by Maureks** [comment]
Wow, thanks man ! 
You're the best ! 
Much appreciated!

**Comment by Maureks** [comment]
Hello again , don't mean to bother , but the way MySQL is being used is giving an error ,
I used this export :

exports.oxmysql:execute

to substitute all the : MySQL.Async.execute

and it works great with no errors on F8 and on live console, and with correct updates on the databse (the other ones were not updating)

on the other way unfortunately , the admin option does not work 

thanks for the attention ! and sorry for the bad english!
