### ISSUE TITLE
/comserv does not work for normal player without admin

### ISSUE THREAD

**Issue by Terranzin** [jaylac2000/qb-communityservice#4]
/comserv and /endcomserv only appears for user who´s admin. When someone on duty + police job they do not even see the explaination when they do /comserv. 

Once they write it, all they get is that "You´re not allowed to use command". If it was something wrong with the job, shouldn´t it atleast say something with "You´re not police" or something? And when they do /com only it does not even popup as a option to pick.

No errors in players Console or server console, just keeps saying that hes not allowed to use the command, like he´s about to use a admin command or something.

**Comment by jaylac2000** [comment]
thats the problem with adding that support. its a pd command not admin command. not sure why someone wanted that. ill just remove admin support and if that person can figure out the issue they can PR or keep it to themself, whatever.
